default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: EngFair_dev

test:
  <<: *default
  database: EngFair_test

production:
  <<: *default
  database: EngFair_prod
